version: 2

models:
  #  SILVER_CUSTOMERS
  - name: silver_customers
    description: Clientes deduplicados y normalizados a partir de los datos crudos
    columns:
      - name: customer_id
        description: Identificador único del cliente
        tests: [unique, not_null]

      - name: email
        description: Dirección de correo electrónico del cliente
        tests: [not_null]

      - name: status
        description: Estado del cliente en el sistema (activo, inactivo, suspendido)
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'Inactive', 'Suspended']

      - name: location_id
        description: FK a la tabla silver_locations
        tests:
          - relationships:
              to: ref('silver_locations')
              field: location_id

      - name: device_id
        description: FK a la tabla silver_devices
        tests:
          - not_null
          - relationships:
              to: ref('silver_devices')
              field: device_id

  #  SILVER_SERVICES
  - name: silver_services
    description: Catálogo de servicios contratables disponibles para los clientes
    columns:
      - name: service_id
        description: Identificador único del servicio
        tests: [unique, not_null]

      - name: service_name
        description: Nombre del servicio estandarizado
        tests: [unique, not_null]

  #  SILVER_DEVICES
  - name: silver_devices
    description: Tabla de dispositivos unicos, con marca y modelo limpios y normalizados
    columns:
      - name: device_id
        description: Identificador único del dispositivo formado a partir de marca y modelo usando un hash md5
        tests: [unique, not_null]

      - name: device_brand
        description: Marca del dispositivo móvil estandarizada
        tests:
          - not_null
          - accepted_values:
              values: ['Xiaomi', 'Huawei', 'Samsung', 'Apple']

      - name: device_model
        description: Modelo del dispositivo móvil
        tests: [not_null]

  #  SILVER_LOCATIONS
  - name: silver_locations
    description: Tabla de ubicaciones por país, ciudad y coordenadas
    columns:
      - name: location_id
        description: Identificador único de la ubicación, formado a partir de país + ciudad + latitud + longitud usando un hash md5
        tests: [unique, not_null]

      - name: country
        description: País normalizado
        tests:
          - not_null
          - accepted_values:
              values:
                ['Argentina', 'Chile', 'Colombia', 'Mexico', 'Peru', 'Unknown']

      - name: city
        description: Ciudad normalizada
        tests: [not_null]

      - name: latitude
        description: Coordenada geográfica latitudinal, entre -90 y 90
        tests: [not_null]

      - name: longitude
        description: Coordenada geográfica longitudinal, entre -180 y 180
        tests: [not_null]

  #  SILVER_CUSTOMERS_SERVICES
  - name: silver_customers_services
    description: Relación N:M entre clientes y los servicios que tienen contratados
    columns:
      - name: customer_id
        description: FK a tabla silver_customers
        tests:
          - not_null
          - relationships:
              to: ref('silver_customers')
              field: customer_id

      - name: service_id
        description: FK a la tabla silver_services
        tests:
          - not_null
          - relationships:
              to: ref('silver_services')
              field: service_id

  #  SILVER PLANS
  - name: silver_plans
    description: Catálogo de planes comerciales con sus características principales
    columns:
      - name: plan_id
        description: Identificador único del plan, formada a partir de plan_type, monthly_data_gb, monthly_bill_usd usando un hash md5
        tests: [unique, not_null]

      - name: plan_type
        description: Tipo de plan contratado (ej. Control, Prepago, Pospago, Unknown en caso de no poder determinarlo)
        tests:
          - not_null
          - accepted_values:
              values: ['Control', 'Prepago', 'Pospago', 'Unknown']

      - name: monthly_data_gb
        description: Cantidad mensual de GB incluidos en el plan
        tests: [not_null]

      - name: monthly_bill_usd
        description: Facturación mensual del plan en USD
        tests: [not_null]

      - name: operator_id
        description: Llave foránea a la tabla de operadores
        tests:
          - not_null
          - relationships:
              to: ref('silver_operators')
              field: operator_id

  # SILVER_CUSTOMERS_PLANS
  - name: silver_customers_plans
    description: Relación entre clientes y planes contratados con detalles de límite y uso actual
    columns:
      - name: customer_id
        description: FK a la tabla silver_customers
        tests:
          - not_null
          - relationships:
              to: ref('silver_customers')
              field: customer_id

      - name: plan_id
        description: FK a la tabla silver_plans
        tests:
          - not_null
          - relationships:
              to: ref('silver_plans')
              field: plan_id

      - name: plan_start_ts
        description: Fecha en la que se detectó por primera vez ese plan activo
        tests: [not_null]

      - name: credit_limit
        description: Límite de crédito asignado al cliente
        tests: [not_null]

      - name: data_usage_current_month
        description: Uso de datos móviles del cliente en el mes actual
        tests: [not_null]

    models:
      - name: silver_payments
        description: Pagos desnormalizados extraídos del campo payment_history de staging_mobile_raw.
        columns:
          - name: customer_id
            description: ID del cliente que realizó el pago
            tests:
              - not_null
              - relationships:
                  to: ref('silver_customers')
                  field: customer_id

          - name: payment_date
            description: Fecha del pago

          - name: payment_amount
            description: Monto pagado por el cliente en ese pago

          - name: payment_status
            description: Estado del pago (Paid, Pending, Failed)
