version: 2

models:
  - name: gold_customer
    description: >
      Dimensión de clientes con atributos demográficos y de referencia
      que cambian muy poco en el tiempo.
    columns:
      - name: customer_id
        description: Identificador único del cliente
        tests: [unique, not_null]

      - name: first_name
        description: Nombre de pila del cliente

      - name: last_name
        description: Apellido del cliente

      - name: email
        description: Correo electrónico de contacto

      - name: age
        description: Edad del cliente (años cumplidos)
        tests: [not_null]

      - name: age_range
        description: Rango de edad en intervalos de 10 años (p. ej. 20-29)
        tests: [not_null]

      - name: registration_date
        description: Fecha en la que el cliente se dio de alta
        tests: [not_null]

      - name: credit_score
        description: Puntuación crediticia numérica
        tests: [not_null]

      - name: credit_bucket
        description: Segmento de crédito derivado del credit_score
        tests: [not_null]

      - name: status
        description: Estado actual del cliente (Active, Suspended, Inactive)
        tests:
          - not_null
          - accepted_values:
              values: ['Active', 'Suspended', 'Inactive']

      - name: city
        description: Ciudad de residencia declarada
        tests: [not_null]

      - name: country
        description: País de residencia declarada
        tests: [not_null]

      - name: region
        description: Región continental derivada del país
        tests: [not_null]

      - name: device_id
        description: FK al dispositivo principal del cliente
        tests:
          - not_null
          - relationships:
              to: ref('gold_device')
              field: device_id

      - name: ingestion_date
        description: Timestamp original de ingesta en la capa Silver

      - name: source
        description: Etiqueta que indica de qué archivo o sistema provino el registro

      - name: run_ts
        description: Timestamp de ejecución del modelo Gold (control de versiones)

  # -----------------------------------------------------
  - name: gold_plan
    description: Dimensión de planes comerciales ofrecidos por la operadora.
    columns:
      - name: plan_id
        description: Identificador único del plan
        tests: [unique, not_null]

      - name: plan_type
        description: Tipo comercial (Prepago, Postpago, Control, Unknown)

      - name: monthly_data_gb
        description: GB de datos incluidos por mes

      - name: monthly_bill_usd
        description: Cargo mensual estándar en USD

      - name: operator_id
        description: FK al operador que comercializa el plan

      - name: run_ts
        description: Timestamp de refresh del modelo Gold

  # -----------------------------------------------------
  - name: gold_operator
    description: Dimensión con información de cada operador móvil.
    columns:
      - name: operator_id
        description: Identificador único del operador
        tests: [unique, not_null]

      - name: operator
        description: Nombre comercial del operador

      - name: run_ts
        description: Timestamp de actualización del modelo Gold

  # -----------------------------------------------------
  - name: gold_device
    description: Dimensión de dispositivos (marca y modelo) utilizados.
    columns:
      - name: device_id
        description: Identificador único hash del dispositivo
        tests: [unique, not_null]

      - name: device_brand
        description: Marca del dispositivo (normalizada)

      - name: device_model
        description: Modelo del dispositivo (normalizado)

      - name: run_ts
        description: Timestamp de ejecución del modelo Gold

  # -----------------------------------------------------
  - name: gold_service
    description: Dimensión de servicios opcionales que pueden contratar los clientes.
    columns:
      - name: service_id
        description: Identificador único del servicio
        tests: [unique, not_null]

      - name: service_name
        description: Nombre descriptivo (Streaming, Roaming, Cloud, etc.)

      - name: run_ts
        description: Timestamp de refresh del modelo Gold

  # -----------------------------------------------------
  - name: gold_date
    description: Dimensión de fecha a nivel mes.
    columns:
      - name: date_month
        description: Primer día del mes (PK)
        tests: [unique, not_null]

      - name: year
        description: Año numérico (YYYY)

      - name: month
        description: Mes numérico (1–12)

      - name: month_name
        description: Nombre del mes (enero, febrero…)

      - name: quarter
        description: Trimestre (1–4)

      - name: is_current_month
        description: Flag TRUE si corresponde al mes en curso

  - name: gold_customer_monthly
    description: Hechos cliente-mes, incluye estado, plan y pagos teóricos.
    columns:
      - name: customer_id
        description: FK al cliente
        tests:
          - not_null
          - relationships: { to: ref('gold_customer'), field: customer_id }

      - name: date_month
        description: FK a la dimensión fecha (primer día del mes)
        tests:
          - not_null
          - relationships: { to: ref('gold_date'), field: date_month }

      - name: plan_id
        description: FK al plan activo en el mes
        tests:
          - relationships: { to: ref('gold_plan'), field: plan_id }

      - name: operator_id
        description: FK al operador del plan activo
        tests:
          - relationships: { to: ref('gold_operator'), field: operator_id }

      - name: is_new_customer
        description: TRUE si este mes es el primero del cliente

      - name: status
        description: Estado del cliente en el mes (Active, Suspended, Inactive)

      - name: credit_score
        description: Score de crédito registrado ese mes

      - name: device_id
        description: FK al dispositivo utilizado en el mes
        tests:
          - relationships: { to: ref('gold_device'), field: device_id }

      - name: monthly_bill_usd
        description: Cargo mensual del plan en USD

      - name: total_paid_usd
        description: Monto efectivamente abonado en el mes

      - name: latest_status
        description: Estado del último pago (Paid, Failed, Pending)

      - name: num_payments
        description: Cantidad de transacciones registradas ese mes

      - name: has_payment_issue
        description: 1 si el pago del mes estuvo pendiente o falló, 0 en caso contrario

  # -----------------------------------------------------
  - name: gold_payment
    description: Hechos de pagos efectuados por cliente y mes.
    columns:
      - name: customer_id
        description: FK al cliente
        tests:
          - not_null
          - relationships: { to: ref('gold_customer'), field: customer_id }

      - name: date_month
        description: FK a la dimensión fecha
        tests:
          - not_null
          - relationships: { to: ref('gold_date'), field: date_month }

      - name: total_paid_usd
        description: Importe total pagado en el mes (USD)

      - name: num_payments
        description: Número de pagos realizados ese mes

      - name: latest_status
        description: Estado del último intento de pago (Paid, Failed, Pending, Late)

  # -----------------------------------------------------
  - name: gold_service_client_monthly
    description: Hechos servicio-cliente-mes, incluye qué servicios están activos.
    columns:
      - name: customer_id
        description: FK al cliente
        tests:
          - not_null
          - relationships: { to: ref('gold_customer'), field: customer_id }

      - name: service_name
        description: Nombre del servicio contratado
        tests: [not_null]

      - name: date_month
        description: FK a la dimensión fecha
        tests:
          - not_null
          - relationships: { to: ref('gold_date'), field: date_month }

      - name: is_active
        description: TRUE si el servicio estaba activo durante el mes seleccionado
